---
driver:
  name: vagrant
  # provider: ovirt3
  # vagrantfiles:
  #   - Vagrantfile.rb

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-15.04
    run_list:
      - recipe[apt]
  - name: centos-7.1
    run_list:
      - recipe[selinux::disabled]
  - name: debian-8.1
    run_list:
      - recipe[apt]
  - name: debian-7.8
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[netatalk::default]
    attributes:

  - name: deb_build
    run_list:
      - recipe[apt]
      - recipe[netatalk::default]
    attributes:
      netatalk:
        install_method: deb_build
    includes: [
      'ubuntu-15.04',
      'debian-7.8',
      'debian-8.1'
    ]
