name 'netatalk'
maintainer 'J. Morgan Lieberthal'
maintainer_email 'j.morgan.lieberthal@gmail.com'
license 'mit'
description 'Installs/Configures netatalk'
long_description 'Installs/Configures netatalk'
version '0.1.0'

depends 'apt', '~> 2.8'
depends 'selinux', '~> 0.9'
